services:
  - type: web
    name: qr-generator
    runtime: python
    rootDirectory: /
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()" --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
    autoDeploy: true
    healthCheckPath: /health
    plan: free